### PR TITLE
[PULL REQUEST] GEOS gfortran build bug

### PR DESCRIPTION
**Pull request by WilliamJamieson**
This commit fixes bugs preventing HEMCO from being built as part of GEOS by the gfortran compiler. This is the result of HEMCO overriding the GEOS compiler flags and the fact that the `MAPL_Base` target will be disappearing from MAPL (it no longer exists in the MAPL `develop` branch.

### CODE REVIEW

**Comment by lizziel** [comment]
Thanks @WilliamJamieson. I would like to update the HEMCO default compiler flag code such that the definitions in HEMCO/CMakeLists.txt will only be used if not defined higher up in the project. This would avoid having to embed them in an if statement excluding the specific super-project (GEOS in your case, but there are others as well). This update would go into 13.0.0.

This would require that GEOS set HEMCO_COMPILER_OPTIONS to avoid the defaults. Do you anticipate a problem with this? It could go into GEOSchem_GridComp CMakeLists.txt. I'm bringing @christophkeller in on this too since he is starting work on using HEMCO in GEOS-Chem in GEOS. We should make sure we (GEOS developers for GOCART and GEOS-Chem) are all using the same version.

Since beyond this change there is only one other part of this PR I am thinking I can bring it in manually and skip to PR merge. I can add HCOI_MAPL_ESMF to Interfaces/GEOS today (sorry that wasn't included before - definitely an oversight when I made the new library). The default compiler flag CMake changes will come later.

**Comment by WilliamJamieson** [comment]
I'm going to bring @tclune into this discussion as well.

**Comment by tclune** [comment]
@lizziel So long as there is a long term solution in 13.0.0 that provides a way for us to use GEOS flags  we are good.    William can certainly work on a branch in the mean time if need be.

**Comment by lizziel** [comment]
I think @LiamBindle did some work to make HEMCO compiler options set from the super project. Liam, can you comment on if this was done for 13.0?

**Comment by LiamBindle** [comment]
Yep, those are included in 13.0. The pull requests are described here: 
- https://github.com/geoschem/HEMCO/pull/58
- https://github.com/geoschem/HEMCO/pull/60

In summary, the PR isolates MAPL, HEMCO, and GC-Classic/GCHP's build properties (specifically, compiler options). This was so we can specify specific compiler options for different components (e.g., turn OMP off in HEMCO specifically).

**Pull request closed without merging**
