### PR TITLE
Remove InvMEGAN manual diagnostics from hcox_megan_mod.F90

### LINKED ISSUE #281: Comment out manual InvMEGAN diagnostic creation code
### Your name

Eloise Marais

### Your affiliation

UCL, UK

### What happened? What did you expect to happen?

This is only sort of a bug. It's a request to comment out unnecessary code that outputs lots of emissions estimates by default when these aren't wanted. Specifically, to comment out calls to Diagn_Create code for all "InvMEGAN_*" variables in the subroutine HCOX_Megan_Init in ./HEMCO/src/Extensions/hcox_megan_mod.F90. These aren't needed, as the user can request these be output from the HEMCO diagnostics file HEMCO_Diagn.rc.
I tested and confirmed that commenting out all these lines, recompiling and rerunning GCClassic with the diagnostics requested via HEMCO_Diagn.rc works. 

### What are the steps to reproduce the bug?

Intentionally left blank, as this is just a quick fix detailed above.

### Please attach any relevant configuration and log files.

Attached a screenshot to show 1 of the 16 diagnostics currently set manually in the code. 
Screenshot 2024-07-08 at 12 48 53

### What HEMCO version were you using?

3.0.0 and 3.6.0 (issue is in both)

### What environment were you running HEMCO on?

Local cluster

### What compiler and version were you using?

gcc 9.2.0

### Will you be addressing this bug yourself?

Yes

### In what configuration were you running HEMCO?

GCClassic

### As what resolution were you running HEMCO?

multiple (4x5, 0.25x0.3125)

### What meterology fields did you use?

GEOS-FP

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by yantosca**
### Name and Institution (Required)

Name: Bob Yantosca
Institution: Harvard + GCST

### Describe the update

This is the companion PR to issue #281 by @eamarais.  We have now removed the calls to `Diagn_Create` that set up manual `InvMEGAN` diagnostics.  These can be scheduled by adding the appropriate entries to `HEMCO_Diagn.rc`.

### Expected changes
This is a zero-diff update.  However, we expect to gain a performance benefit by not having to update the manual diagnostics on each HEMCO timestep.

### Related Github Issue
- Closes #281

### CODE REVIEW

**Comment by yantosca** [comment]
Integration tests are now in progress.

**Comment by yantosca** [comment]
Integration tests are in progress.

**Comment by yantosca** [comment]
All GEOS-Chem Classic integration tests passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

GCClassic #8730985 GEOS-Chem submod update: Merge PR #2372 (Disable MEGAN in non-bmk sims)
GEOS-Chem #03287a67a Merge PR #2372 (Turn off MEGAN extension for non-benchmark sims)
HEMCO     #ebd4177 Remove InvMEGAN manual diagnostics from hcox_megan_mod.F90

Using 24 OpenMP threads
Number of execution tests: 28

Submitted as SLURM job: 39699970
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
All tests were zero-diff w/r/t PR #2372, except:
- TOMAS (parallelization error?)
- APM (parallelization error?)

Also, differences were noted in the HEMCO diagnostics output for the following simulations:
- fullchem_benchmark
- tagCO

This is because the following variables are no longer included in the diagnostic output:
```console
float InvMEGAN_AAXX(time, lat, lon) ;
float InvMEGAN_FAXX(time, lat, lon) ;
float InvMEGAN_MBOX(time, lat, lon) ;
float InvMEGAN_OSQT(time, lat, lon) ;
float InvMEGAN_BCAR(time, lat, lon) ;
float InvMEGAN_FARN(time, lat, lon) ;
float InvMEGAN_OMON(time, lat, lon) ;
float InvMEGAN_OCIM(time, lat, lon) ;
float InvMEGAN_CARE(time, lat, lon) ;
float InvMEGAN_MYRC(time, lat, lon) ;
float InvMEGAN_SABI(time, lat, lon) ;
float InvMEGAN_BPIN(time, lat, lon) ;
float InvMEGAN_APIN(time, lat, lon) ;
float InvMEGAN_ACET_DIRECT(time, lat, lon) ;
float InvMEGAN_ACET_MBOX(time, lat, lon) ;
```

**Comment by yantosca** [comment]
All GCHP integration tests passed:
```console
==============================================================================
GCHP: Execution Test Results

GCHP      #094f53b GEOS-Chem submod update: Merge PR #2372 (Disable MEGAN in non-bmk sims)
GEOS-Chem #03287a67a Merge PR #2372 (Turn off MEGAN extension for non-benchmark sims)
HEMCO     #

Number of execution tests: 11

Submitted as SLURM job: 39700133
==============================================================================
 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
Also, all tests were identical to PR #2372.  Differences were noted in the Emissions collection file, but this is because the following diagnostics are no longer included:
```console
float InvMEGAN_AAXX(time, lat, lon) ;
float InvMEGAN_FAXX(time, lat, lon) ;
float InvMEGAN_MBOX(time, lat, lon) ;
float InvMEGAN_OSQT(time, lat, lon) ;
float InvMEGAN_BCAR(time, lat, lon) ;
float InvMEGAN_FARN(time, lat, lon) ;
float InvMEGAN_OMON(time, lat, lon) ;
float InvMEGAN_OCIM(time, lat, lon) ;
float InvMEGAN_CARE(time, lat, lon) ;
float InvMEGAN_MYRC(time, lat, lon) ;
float InvMEGAN_SABI(time, lat, lon) ;
float InvMEGAN_BPIN(time, lat, lon) ;
float InvMEGAN_APIN(time, lat, lon) ;
float InvMEGAN_ACET_DIRECT(time, lat, lon) ;
float InvMEGAN_ACET_MBOX(time, lat, lon) ;
```

**Review by msulprizio — APPROVED** [review]
This is a straightforward pull request, simply removing the manual diagnostics code from the MEGAN extension. Looks good to merge.

**Pull request merged**
