### PR TITLE
[PULL REQUEST] Add climatology input for volcano extension

### PR DESCRIPTION
**Pull request by msulprizio**
The HEMCO volcano extension has been updated her to include an input for volcano climatology via the `Volcano_Climatology` setting in HEMCO_Config.rc.

```
117     Volcano                : on    SO2
    --> Volcano_Source         :       AeroCom
    --> Volcano_Table          :       $ROOT/VOLCANO/v2021-09/$YYYY/$MM/so2_volcanic_emissions_Carns.$YYYY$MM$DD.rc
    --> Volcano_Climatology    :       $ROOT/VOLCANO/v2021-09/so2_volcanic_emissions_CARN_v202005.degassing_only.rc
 
```

The volcano extension will first look for a volcano file for the current simulation date. If that file is not found, it will then attempt to look for the climatology file. If neither file is found, the simulation will crash with an error.

See corresponding GEOS-Chem PR https://github.com/geoschem/geos-chem/pull/921.

### CODE REVIEW

**Review by yantosca — COMMENTED** [review]
This looks OK but I think it might affect the dry-run simulation.  We need it to print out either "HEMCO (VOLCANO): Opening" or "HEMCO (VOLCANO): REQUIRED FILE NOT FOUND" if it is a dry-run.  (Although the dry-run script may just key on "NOT FOUND".

Can you do a quick dry-run to test this?

**Comment by msulprizio** [comment]
@yantosca Yes, I can do a dry-run test on this as well. The way I coded it, the dry run will look for the file for the simulation date only (as it did before). It will not proceed to look for the climatology file. I did it this way because otherwise the dry-option would always proceed to look for and download the climatology if the updated volcano emissions aren't downloaded.

**Comment by yantosca** [comment]
> 
> 
> @yantosca Yes, I can do a dry-run test on this as well. The way I coded it, the dry run will look for the file for the simulation date only (as it did before). It will not proceed to look for the climatology file. I did it this way because otherwise the dry-run option would always proceed to look for and download the climatology if the updated volcano emissions aren't downloaded.

I see.  Then this should be OK.  If the dry-run test works then you can merge into dev.

**Comment by msulprizio** [comment]
@yantosca I just pushed another commit to this PR so that the dry-run option also looks for the climatology file if it can't find the volcano emissions file for the simulation date. I verified this works with the dry-run option. From `dryrun.log`:

```
HEMCO (VOLCANO): REQUIRED FILE NOT FOUND /n/holyscratch01/external_repos/GEOS-CHEM/gcgrid/gcdata/ExtData/HEMCO/VOLCANO/v2021-08/2019/07/so2_volcanic_emissions_Carns.20190701.rc
Attempting to read volcano climatology file 
HEMCO (VOLCANO): CLIMATOLOGY FILE NOT FOUND /n/holyscratch01/external_repos/GEOS-CHEM/gcgrid/gcdata/ExtData/HEMCO/VOLCANO/v2021-08/so2_volcanic_emissions_CARN_v202005.degassing_only.rc
```
 and from `dryrun.log.unique`:
 
 ```
/n/holyscratch01/external_repos/GEOS-CHEM/gcgrid/gcdata/ExtData/HEMCO/VOLCANO/v2021-08/2019/07/so2_volcanic_emissions_Carns.20190701.rc
/n/holyscratch01/external_repos/GEOS-CHEM/gcgrid/gcdata/ExtData/HEMCO/VOLCANO/v2021-08/2019/07/so2_volcanic_emissions_Carns.20190702.rc
/n/holyscratch01/external_repos/GEOS-CHEM/gcgrid/gcdata/ExtData/HEMCO/VOLCANO/v2021-08/so2_volcanic_emissions_CARN_v202005.degassing_only.rc
 ```

**Pull request merged**
