### PR TITLE
Add emission factors for ALK6, C4H6, EBZ, STYR, TMB emissions in GFED and FINN biomass burning

### PR DESCRIPTION
**Pull request by yantosca**
### Name and Institution (Required)

Name: Bob Yantosca
Institution: Harvard + GCST

### Describe the update
This is the companion PR to https://github.com/geoschem/geos-chem/issues/2390.  This adds emission factors for new the species (from @kelvinb) in the chemistry updates from Travis et al 2023 (see PR https://github.com/geoschem/geos-chem/pull/2318).

### Expected changes
- Need more information

### Reference(s)
- Travis et al 2023:  https://egusphere.copernicus.org/preprints/2024/egusphere-2024-951/
- Other references?

### Related Github Issue
- Should be merged concurrently with https://github.com/geoschem/geos-chem/pull/2318
- Closes https://github.com/geoschem/geos-chem/issues/2390

### CODE REVIEW

**Comment by yantosca** [comment]
Heads up @msulprizio @lizziel @yuanjianz @yidant: This PR will affect biomass burning emissions, as there are several new species being added.  These species will have to be added to the offline emissions.  In the meantime, I think we would have to activate GFED4 by default to provide emissions for these species even when using the current offline emissions.

**Comment by yantosca** [comment]
All GCHP integration tests passed:
```console

==============================================================================
GCHP: Execution Test Results

GCHP      #136fa70 GEOS-Chem submod update: Merge PR #2398 (Uncomment cations for HETP)
GEOS-Chem #38b6d1801 Update HEMCO_Config.rc for CESM with Kelvin Bates emissions updates
HEMCO     #

Number of execution tests: 11

Submitted as SLURM job: 42874275
==============================================================================
 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
All GEOS-Chem Classic integration tests passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

GCClassic #6f22240 GEOS-Chem submod update: Merge PR #2398 (Uncomment cations for HETP)
GEOS-Chem #38b6d1801 Update HEMCO_Config.rc for CESM with Kelvin Bates emissions updates
HEMCO     #3076296 Species ACR should use index #41 in hcox_gfed_include_gfed4.H

Using 24 OpenMP threads
Number of execution tests: 28

Submitted as SLURM job: 42874229
==============================================================================
 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Review by msulprizio — APPROVED** [review]
This update looks good to merge.

Note that we should generate an updated GFED climatology file that includes these species. I have created a feature request at https://github.com/geoschem/geos-chem/issues/2415.

**Comment by yantosca** [comment]
Thanks @msulprizio!

**Comment by ktravis213** [comment]
@kelvinhb what about ACR emissions?

**Comment by yantosca** [comment]
@ktravis213 @kelvinhb: Yes, ACR is now a GFED species.  See the config file:
```console
111     GFED                   : ${RUNDIR_GFED_EXT}   NO/CO/ALK4/ACET/MEK/ALD2/PRPE/C2H2/C2H4/C3H8/CH2O/C2H6/SO2/NH3/BCPO/BCPI/OCPO/OCPI/POG1/POG2/MTPA/BENZ/TOLU/XYLE/NAP/EOH/MOH/SOAP/FURA/PHEN/MVK/ISOP/ACTA/MGLY/GLYX/RCHO/HCOOH/ACR/STYR/C4H6
```

**Comment by yantosca** [comment]
This PR was merged at the same time as GEOS-Chem PR https://github.com/geoschem/geos-chem/pull/2318.

**Pull request merged**
